# Cloudflare Pages Configuration
name = "seo-health-check-tool"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages Functions Configuration
[build]
command = "echo 'No build required for static site'"
publish = "."

# Environment Variables (configure in Cloudflare Dashboard)
# Go to: Pages > Your Project > Settings > Environment variables
[env.production.vars]
# Required:
# - PAGESPEED_API_KEY: Google PageSpeed Insights API key
#
# Optional (for enhanced features):
# - OPENAI_API_KEY: ChatGPT API for AI-powered SEO recommendations
# - GOOGLE_SEARCH_CONSOLE_CLIENT_ID: Google Search Console integration
# - GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET: Google Search Console integration
#
# Note: Do NOT store actual API keys in this file!
# Add them via Cloudflare Dashboard: Settings > Environment variables

[env.preview.vars]
# Preview environment variables (optional)
# Add same variables here if you want them available in preview deployments